#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    project_rooter_patterns = ['Cargo.toml', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
    # project_rooter_automatically = false
    statusline_separator = "slant"
    statusline_iseparator = "slant"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filetree_direction = "right"
    vim_help_language = "cn"
    autocomplete_method = "coc"
    filemanager = "defx"
    # statusline_left_sections = [
       # 'winnr',
       # 'major mode',
       # 'filename',
       # 'version control info',
       # 'search status'
    # ]
    # right sections of statusline
    statusline_right_sections = [
       'fileformat',
       'minor mode lighters',
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]
[[layers]]
name = "incsearch"
[[layers]]
    name = "colorscheme"
[[layers]]
    name = 'autocomplete'
    # auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"
    cycle = true
[[layers]]
  name = "format"
[[layers]]
  name = "lang#xml"
[[layers]]
  name = "tools#dash"
[[layers]]
  name = "sudo"
[[layers]]
  name = "tmux"
[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 16
[[layers]]
  name = "git"
  git_plugin = 'fugitive'
[[layers]]
  name = "chinese"
[[layers]]
  name = "fzf"
[[layers]]
  name = "tools"

